defaults:
  target: "Kessel"
  scaler: "0.001"

sensor:
  - platform: template
    name: ${scaled_property}
    id: ${scaled_property}
    state_class: "measurement"
    accuracy_decimals: 3
    internal: true
    filters:
      - multiply: ${scaler}

  - platform: template
    name: ${sensor_name}
    id: ${sensor_name}
    unit_of_measurement: ${unit}
    icon: ${icon}
    accuracy_decimals: ${accuracy_decimals}
    state_class: "total_increasing"

esphome:
  on_boot:
    priority: 100.0 # AFTER_CONNECTION
    then:
      - lambda: |-
          CallbackHandler::instance().addCallback(std::make_pair(${target},Property::k${scaled_property}),[](const SimpleVariant& value){
            id(${scaled_property}).publish_state(value.get<std::uint16_t>());
          });
          CallbackHandler::instance().addCallback(std::make_pair(${target},Property::k${property}),[](const SimpleVariant& value){
            id(${sensor_name}).publish_state(value.get<std::uint16_t>() + id(${scaled_property}).state);
          });
